// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzywlzqrgkvjozdeiwck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6eXdsenFyZ2t2am96ZGVpd2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODA1NTEsImV4cCI6MjA2NDM1NjU1MX0.PhquYh4fVZUPDB--z2h3BV0iyxDF0X4WnPuSG5XSCNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);